### ISSUE TITLE
Current master fails to build. This is because Makefile.am mentions "icons/icons.c", which isn't in master. What happened?

### ISSUE THREAD

**Issue by unforgettableid** [juddmon/jpilot#10]
Hi!

The lastest commit to master is 81080f1, which was committed last October.  It was a patch kindly contributed by Ng Oon-Ee (@ngoonee).  The patch never appeared on the mailing list, or in any issue, or in any pull request.  Instead, Oon-Ee, I'm guessing that you probably emailed it directly to @juddmon, who then checked it in directly.

But the very beginning of [the commit](https://github.com/juddmon/jpilot/commit/81080f111e88b3c2d623b0a7406fe89fb3009163) adds mention of "icons/icons.c" to Makefile.am.  I looked in the Git master branch and didn't see any "icons/icons.c" there.  This is why the master branch now fails to build.

The rest of the commit seems to have nothing to do with icons; it is all about adding Contacts support to jpilot-dump.

I wonder:

A)  Does anyone still have the original patch message handy?

B)  Did someone recently create an "icons.c" file which never got emailed to Judd or checked into Git?

C)  Or were they perhaps merely planning to create such a file, though they never actually created it?

D)  In the end, how might mention of "icons/icons.c" have made it into Makefile.am?

Thanks in advance.

P.S.  I thank you both for your work on J-Pilot!  I use it quite regularly, and have even mentioned it at http://www.reddit.com/r/Palm/ once or twice, and I in general find it quite useful.

**Comment by ngoonee** [comment]
Sorry to say but I've not used jpilot in years (or any palm device really)
and don't really remember what I did. The patch must have been submitted
back in 2010 or something along those lines.

**Comment by unforgettableid** [comment]
Ah; thank you Oon-Ee.  After seeing your reply, I searched deeper.  Your patch[1] was indeed submitted to the list, back in '09.  It was attached to a message[2] which might have been forgotten, deep in Judd's inbox, for years.  These things can happen; as the former maintainer of a tiny open-source project, I understand completely.

Oon-Ee, your patch only adds mention of "contact.c" to Makefile.am.  But somehow, @juddmon, you managed to also add mention of "icons/icons.c" to the final commit.  :)

Judd, may I ask?:  Did you ever create an "icons/icons.c" file which hasn't yet been checked in?

Thanks in advance!

^  [1].  http://lists.jpilot.org/pipermail/jpilot_lists.jpilot.org/attachments/20090921/2c07516e/attachment.patch
^  [2].  http://lists.jpilot.org/pipermail/jpilot_lists.jpilot.org/2009-September/008294.html

**Comment by juddmon** [comment]
I just added icons/icons.c and a clean checkout built for me.  I am still around supporting whatever Palm die-hards are left.  Thanks for the mentions on Reddit.

**Comment by unforgettableid** [comment]
I'm not 100% sure what [icons.c](https://github.com/juddmon/jpilot/blob/master/icons/icons.c) is for. Maybe it's for building one or more icons directly into the J-Pilot binary, which seems to me to be a good idea.

If you please, feel free to add a comment to the beginning of icons.c saying what it's for.  :)

Anyway, thank you very much for your reply, and for checking the file in!  Closing.
