### ISSUE TITLE
Question: How to bulk delete all contacts?

### ISSUE THREAD

**Issue by hub2git** [juddmon/jpilot#14]
I have over a thousand contacts in jpilot 1.8.2 (linux mint 18.2). How do I delete all of them?

**Comment by juddmon** [comment]
If you are not using a PalmOS device to sync with then just delete ContactsDB-PAdd.pdb and ContactsDB-PAdd.pc3.  If you are using a PalmOS device you could hard reset it, or try installing ContactsDB-PAdd.pdb from /usr/share/jpilot.

Questions will get answered faster on the jpilot mailing list.  http://jpilot.org/lists/
