### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by misterwrong** [juddmon/jpilot#28]
Build in master fails after these messages:
```
configure.in:380: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
Removing line 380 from configure.in appears to allow the script to continue.

This occurs in both master and feature-gtk3

**Comment by juddmon** [comment]
You need to have the gcrypt package installed.  On debian this is libgcrypt20-dev.  I can't find anyway to make autoconf conditionally depend on a macro being available or not.  I could however build the configure with libgrypt installed and then the configure would work on systems without it.
