### ISSUE TITLE
Fix for tabs having a white background in default theme

### ISSUE THREAD

**Issue by sulph68** [juddmon/jpilot#29]
The current GTK3 "jpilotcss.default" theme has some issues where 
1) the initial font defaults to "Arial Black" instead of "Arial"
2) the tabs in the backrgound are a jarring white.

I suggest the following fixes in jpilotcss.default

`
/* @define-color notebook_unselected_tab #dcdad8; */
@define-color notebook_unselected_tab @theme_bg_color;
`
and

`* {
    font-family: Arial, sans-serif;
    font-size: 11pt;
}`

**Comment by unforgettableid** [comment]
It looks like nobody looked at your report :(

I, unfortunately, am not a maintainer of any branch of J-Pilot, and cannot make any changes to any file.

Could you please try the following instead?

A.)  Send a pull request with your suggested fixes.  
B.)  In the pull request's comments, ping the file's maintainer.
C.)  Reply to this comment with a link to the pull request.

Thank you!

**Comment by unforgettableid** [comment]
@dmalia1:  If you could please take a look at @sulph68's suggested fixes (above), this would be most excellent!  :)

**Comment by juddmon** [comment]
Github was not sending me emails for a long time.  I think it is now.  @unforgettableid if you get to this before me let me know.

**Comment by dmalia1** [comment]
I'm on a lot of 'git' repos at work, and I missed these as well.  anyway. 
https://github.com/juddmon/jpilot/pull/35 should fix this.

**Comment by juddmon** [comment]
I merged #35.

**Comment by juddmon** [comment]
I merged https://github.com/juddmon/jpilot/pull/35. #35
