### ISSUE TITLE
Could you please appoint some co-maintainers? I'm willing to volunteer.

### ISSUE THREAD

**Issue by unforgettableid** [juddmon/jpilot#33]
Dear @juddmon:

## The problem

"The reasons for dedicating less time to or even leaving an open source project are many and varied. Maintainers leave their company or lose interest. Changes in their personal lives give them less time to take care of the project, or they stop their activities in the open source scene entirely because of burnout or illness. In the worst case, they have passed away.

"In all these cases, projects are left behind, often with no one but the original author having administration rights or access to the publishing accounts. Of course, you can fork and publish a project under a new name. But, ultimately, that leads to confusion about the state of the project and whether it can and should still be considered a stable piece of software."  [(Source.)](https://opensource.com/article/20/5/adoptoposs)

## The solution

"...  Each and every open source project of considerable popularity should have a team of co-maintainers to avoid sliding into neglect. Multiple people should have full access to the project and all related services -- like package registries, hosting accounts, and third-party services -- to ensure ongoing maintenance even as maintainers come and go.  ...

"Your co-maintainers do not necessarily need to work on the project every day. They might only be an in-case-of-emergency contact, but at least they will be able to be there. This process often means giving new maintainers access when former maintainers want to step down."  [(Source.)](https://opensource.com/article/20/5/adoptoposs)

## My suggestion

My biased suggestion would be to invite @dmalia1, @nforro, and myself to be co-maintainers of this GitHub repository.  If we accept your invitation, perhaps we can help to review old pull requests and/or otherwise make ourselves useful.  Or, if not, at least we can help to make sure that the torch gets passed on if someone competent and new expresses interest in helping out.

Each of the three of us has had at least one pull request accepted to at least one branch of J-Pilot.

In addition, you could also invite @eklausme, who maintains [the J-Pilot package for Arch Linux](https://aur.archlinux.org/packages/jpilot).

## How to invite new co-maintainers

If you wish to invite new co-maintainers:

*  Visit https://github.com/juddmon/jpilot/settings/access.
*  Click the big green "Add people" button.
*  Enter a prospective co-maintainer's GitHub username.

GitHub can then email the person a co-maintainership invitation.  The person can accept or decline.

## Conclusion

Dear @juddmon:

Are you possibly interested in sending out co-maintainership invitations to the individuals of your choosing?

**Comment by juddmon** [comment]
Sure, just please commit good code ;-)
