### ISSUE TITLE
Typo in description of pi-dlp.h

### ISSUE THREAD

**Issue by CoSoCo** [juddmon/jpilot#40]
In the description of `dlp_VFSDirEntryEnumerate` there is:
...  **of** the iterator becomes #vfsIteratorStop.
I guess, it shoud be:
...  **or** the iterator becomes #vfsIteratorStop.

**Comment by CoSoCo** [comment]
Here is a patch:
[0005-Fixed-typo-in-description-of-pi-dlp.h.patch.zip](https://github.com/juddmon/jpilot/files/9339796/0005-Fixed-typo-in-description-of-pi-dlp.h.patch.zip)

**Comment by juddmon** [comment]
This is in pilot-link.  I have pushed this change to my master branch.

**Comment by CoSoCo** [comment]
That's great.
But I don't see the change in your repo. I get:
[This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.](https://github.com/juddmon/pilot-link/commit/a3dd7b40a3d3dcb66a79651b9bb507982ad6ed31)

**Comment by juddmon** [comment]
I committed to to David's repo because I want to keep these in sync if
possible.  I just did an upstream pull.

https://github.com/desrod/pilot-link/commit/a3dd7b40a3d3dcb66a79651b9bb507982ad6ed31

Judd
