### ISSUE TITLE
Shipping the Pics&Videos plugin with J-Pilot

### ISSUE THREAD

**Issue by unforgettableid** [juddmon/jpilot#46]
There's a Pics&Videos plugin available for J-Pilot, thanks to @danbodoh and @CoSoCo.

https://github.com/danbodoh/picsnvideos-jpilot

Because it's not included with J-Pilot, some users might not know that it exists.

A.)  I've never tried it.  How reliably does it work?

B.)  Would it possibly make sense to ship the plugin with J-Pilot, or even to merge the code directly into the J-Pilot source tree?

C.)  If not, could we at least add a link from the J-Pilot README file to the plugin's homepage?

**Comment by juddmon** [comment]
@danbodoh and @CoSoCo Let me know if you would like to take route B.

**Comment by danbodoh** [comment]
Judd,
CoSoCo prompted me to get the code to GitHub, and changes from CoSoCo have
been merged into danbodoh/picsnvideos-jpilot: An old plugin for JPilot to
download pictures from Palm Treo, Centro and other devices (github.com)
<https://github.com/danbodoh/picsnvideos-jpilot>

I don't mind shipping Pics And Videos with a binary distribution of JPilot,
but I'd prefer the codebase be in my repository.

Dan

**Comment by juddmon** [comment]
@danbodoh No problem at all and that is probably my preferred option.  I added your link to my README, so option C is completed.

**Comment by CoSoCo** [comment]
I agree to Dan and Judd.
