### ISSUE TITLE
Keeping J-Pilot 2.x in the default branch of the repository

### ISSUE THREAD

**Issue by unforgettableid** [juddmon/jpilot#47]
Hi!

A.)  Nowadays, do you recommend that members of the general public should preferably use J-Pilot 1.8.x or 2.x?

B.)  I notice that J-Pilot 2.x is hidden away in [its own branch](https://github.com/juddmon/jpilot/branches) of the repository.  If it's the recommended version nowadays, then I wonder if you could please rearrange things?  It might be better if you could please put J-Pilot 2.x on the default branch, and could please consign J-Pilot 1.8.x to its own lonely branch.

**Comment by unforgettableid** [comment]
Possibly related:  #48.

**Comment by juddmon** [comment]
I merged feature-gtk3 into master and master can be the default branch.
