### ISSUE TITLE
Ubuntu 24.04 LTS support

### ISSUE THREAD

**Issue by tomchiverton** [juddmon/jpilot#58]
I'm sure I'm not the first person to ask what's standing in the way of this ?

**Comment by juddmon** [comment]
You are the first person to ask.  When I get some time I'll install 24.04 and build a new version.

**Comment by tomchiverton** [comment]
According to https://lists.jpilot.org/empathy/thread/OEAZ4D5K5NLQG5EMOKK33PICEW745U6W it doesn't even need to be built, just add the current versions to the newer distro's release

**Comment by juddmon** [comment]
It is a little more than that since I don't own package cloud.  I have compiled a new jpilot version 2.0.2 and uploaded it as an Ubuntu 22.04 and 24.04 compatible package.
